// <auto-generated />
using System;
using AgenciaFull.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgenciaFull.Migrations
{
    [DbContext(typeof(AgenciaFullContext))]
    [Migration("20240218194057_AgenciaFullDB")]
    partial class AgenciaFullDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgenciaFull.Models.Hospedagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Destino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Entrada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hoteis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quarto")
                        .HasColumnType("int");

                    b.Property<DateTime>("Saida")
                        .HasColumnType("datetime2");

                    b.Property<int>("Viajantes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hospedagem");
                });

            modelBuilder.Entity("AgenciaFull.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("AgenciaFull.Models.Pacote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Destino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ida")
                        .HasColumnType("datetime2");

                    b.Property<string>("Origem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quarto")
                        .HasColumnType("int");

                    b.Property<int>("Viajantes")
                        .HasColumnType("int");

                    b.Property<DateTime>("Volta")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Pacote");
                });

            modelBuilder.Entity("AgenciaFull.Models.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CartaoCredito")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Pix")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Pagamento");
                });

            modelBuilder.Entity("AgenciaFull.Models.Passageiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PacoteId")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PacoteId");

                    b.ToTable("Passageiro");
                });

            modelBuilder.Entity("AgenciaFull.Models.Passagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Destino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ida")
                        .HasColumnType("datetime2");

                    b.Property<string>("Origem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Viajantes")
                        .HasColumnType("int");

                    b.Property<DateTime>("Volta")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Passagem");
                });

            modelBuilder.Entity("AgenciaFull.Models.Passageiro", b =>
                {
                    b.HasOne("AgenciaFull.Models.Pacote", "Pacote")
                        .WithMany("Passageiro")
                        .HasForeignKey("PacoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pacote");
                });

            modelBuilder.Entity("AgenciaFull.Models.Pacote", b =>
                {
                    b.Navigation("Passageiro");
                });
#pragma warning restore 612, 618
        }
    }
}
